### ISSUE TITLE
Create a project scope document

### ISSUE THREAD

**Issue by osioke** [frintern/wipe#1]
To create this, you can use this guide - https://skillguides.byfrintern.com/skills/5/learn-project-management

**Comment by osioke** [comment]
@sage-godspeed please add a link to the initial draft of the project scope document here, so we can keep track of changes and others can learn from this.

**Comment by sage-godspeed** [comment]
[WIPE Project Scope Document](https://docs.google.com/document/d/17Y8eQea_WpgSccDLcupniYkSIseGDqTzOcGJfpANLQA/edit?usp=sharing)
[WasteUp - Uber for Waste](https://docs.google.com/document/d/1y35pRuTAOX_6muVF5xrN-Yc2aJW7Uda-k6rCQ_qxxDI/edit?usp=sharing)

**Comment by sage-godspeed** [comment]
done

**Comment by sage-godspeed** [comment]
The wasteup (uber for waste) project scope document received an update to allow a switch from waterfall project management methodology to Agile in order to simulate a startup's product build process. Find the project scope here - 
[WasteUp - Uber for Waste](https://docs.google.com/document/d/1y35pRuTAOX_6muVF5xrN-Yc2aJW7Uda-k6rCQ_qxxDI/edit?usp=sharing)

**Comment by osioke** [comment]
The project brief has been reviewed and accepted, this task is done.

Awesome work @sage-godspeed!

**Comment by soheilpaper** [comment]
Hi, take a look at the below [medium post ](https://elasa2next.medium.com/introducing-the-initial-idea-of-a-project-in-the-field-of-waste-management-through-cyberspace-d888f853b7c0)and it [GitHub repository:](https://github.com/Startup-Data/SatLunNeh)


![image](https://user-images.githubusercontent.com/6679151/138072417-db2b369f-d5c5-4e2a-9bcf-44cbf1830cf2.png)

If you like to contact me, use[ this link](https://web.whatsapp.com/send?phone=989155253009) for WhatsApp contact.
